### PR TITLE
Replace foo with name

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Well, that's the point the two might not correspond

**Comment by rgrinberg** [comment]
Hmm, I'm definitely misunderstand something. So what should I pass to `-n`? The name of the package currently being pinned (Which is just `name`)? Or some sort of "parent" name common to all packages?

**Comment by ghost** [comment]
Basically when you do `topkg distrib`, only one name will be used, typically the name of the project on github. This is what you want to pass. When all the packages in your project follow the scheme `name(-.*)?`, jbuilder will assume the name is `name`.

**Comment by rgrinberg** [comment]
I see, thanks.

**Pull request closed without merging**
